version: '3'
services:
  flaskapp:
    build: ./webapp
    volumes:
      - ./webapp:/app
    ports:
      - "80:80"
    environment:
      - FLASK_ENV=development
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=cases123
      - MYSQL_DB=case_studies
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: cases123
      MYSQL_DATABASE: case_studies
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

volumes:
  db_data: